from pathlib import Path

p = Path('source/PlayableShelterSession.cpp')
s = p.read_text()

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'missing {label}')
    s=s.replace(old,new,1)

rep('''constexpr std::uint16_t kPlayableSaveVersionV1 = 1u;\nconstexpr std::uint16_t kPlayableSaveVersionV2 = 2u;\nconstexpr std::size_t kPlayableSaveHeaderSize = 16u;''', '''constexpr std::uint16_t kPlayableSaveVersionV1 = 1u;\nconstexpr std::uint16_t kPlayableSaveVersionV2 = 2u;\nconstexpr std::uint16_t kPlayableSaveVersionV3 = 3u;\nconstexpr std::size_t kPlayableSaveHeaderSize = 16u;''','version const')
rep('''constexpr std::size_t kPlayableSavePayloadSizeV2 =\n    (kPlayableSaveScalarCountV2 +\n     static_cast<std::size_t>(kPlayableMaxRooms) * 2u +\n     static_cast<std::size_t>(kPlayableRoomCapacity) *\n         kPlayableRoomFieldCountV2 +\n     static_cast<std::size_t>(kPlayableResidentCount) *\n         kPlayableResidentFieldCountV2) *\n    sizeof(std::int32_t);''', '''constexpr std::size_t kPlayableSavePayloadSizeV2 =\n    (kPlayableSaveScalarCountV2 +\n     static_cast<std::size_t>(kPlayableMaxRooms) * 2u +\n     static_cast<std::size_t>(kPlayableRoomCapacity) *\n         kPlayableRoomFieldCountV2 +\n     static_cast<std::size_t>(kPlayableResidentCount) *\n         kPlayableResidentFieldCountV2) *\n    sizeof(std::int32_t);\nconstexpr std::size_t kPlayableSavePayloadSizeV3 =\n    kPlayableSavePayloadSizeV2 + sizeof(std::uint64_t) +\n    static_cast<std::size_t>(kPlayableRoomCapacity) *\n        (sizeof(std::uint64_t) * 2u + sizeof(std::int32_t));''','payload const')
rep('''void normalize_room_groups(PlayableShelterState& state) noexcept {\n    std::uint64_t highest_id = 0;\n    for (auto& room : state.room_entries) {\n        if (!room.active) continue;\n        if (room.segment_id == 0) room.segment_id = state.next_segment_id++;\n        highest_id = std::max(highest_id, room.segment_id);\n        room.group_id = room.segment_id;\n        room.level = std::max(1, std::min(room.level, kPlayableMaximumRoomLevel));\n    }\n    state.next_segment_id = std::max(state.next_segment_id, highest_id + 1);\n''', '''void normalize_room_groups(PlayableShelterState& state) noexcept {\n    std::uint64_t highest_id = 0;\n    for (const auto& room : state.room_entries) {\n        if (room.active) highest_id = std::max(highest_id, room.segment_id);\n    }\n    state.next_segment_id = std::max(state.next_segment_id, highest_id + 1);\n    for (int floor = 0; floor < kPlayableGridFloors; ++floor) {\n        for (int column = 0; column < kPlayableGridColumns; ++column) {\n            const int index = room_index_at_state(state, column, floor);\n            if (index < 0) continue;\n            auto& room = state.room_entries[static_cast<std::size_t>(index)];\n            if (room.segment_id == 0) room.segment_id = state.next_segment_id++;\n            room.group_id = room.segment_id;\n            room.level = std::max(1, std::min(room.level, kPlayableMaximumRoomLevel));\n        }\n    }\n''','normalize ids')
rep('''void append_u32(std::vector<std::uint8_t>& output,\n                std::uint32_t value) {\n    for (int shift = 0; shift < 32; shift += 8) {\n        output.push_back(static_cast<std::uint8_t>(value >> shift));\n    }\n}\n''','''void append_u32(std::vector<std::uint8_t>& output,\n                std::uint32_t value) {\n    for (int shift = 0; shift < 32; shift += 8) {\n        output.push_back(static_cast<std::uint8_t>(value >> shift));\n    }\n}\n\nvoid append_u64(std::vector<std::uint8_t>& output,\n                std::uint64_t value) {\n    for (int shift = 0; shift < 64; shift += 8) {\n        output.push_back(static_cast<std::uint8_t>(value >> shift));\n    }\n}\n''','append u64')
rep('''bool read_u32(const std::vector<std::uint8_t>& input,\n              std::size_t& offset,\n              std::uint32_t& value) noexcept {\n    if (offset + 4u > input.size()) return false;\n    value = 0u;\n    for (int shift = 0; shift < 32; shift += 8) {\n        value |= static_cast<std::uint32_t>(input[offset++]) << shift;\n    }\n    return true;\n}\n''','''bool read_u32(const std::vector<std::uint8_t>& input,\n              std::size_t& offset,\n              std::uint32_t& value) noexcept {\n    if (offset + 4u > input.size()) return false;\n    value = 0u;\n    for (int shift = 0; shift < 32; shift += 8) {\n        value |= static_cast<std::uint32_t>(input[offset++]) << shift;\n    }\n    return true;\n}\n\nbool read_u64(const std::vector<std::uint8_t>& input,\n              std::size_t& offset,\n              std::uint64_t& value) noexcept {\n    if (offset + 8u > input.size()) return false;\n    value = 0u;\n    for (int shift = 0; shift < 64; shift += 8) {\n        value |= static_cast<std::uint64_t>(input[offset++]) << shift;\n    }\n    return true;\n}\n''','read u64')
anchor='''    if (offset != body.size()) return false;\n    normalize_room_groups(state);\n    return valid_playable_state(state);\n}\n\n}  // namespace\n'''
reader='''    if (offset != body.size()) return false;\n    normalize_room_groups(state);\n    return valid_playable_state(state);\n}\n\nbool read_v3_payload(const std::vector<std::uint8_t>& body,\n                     PlayableShelterState& state) noexcept {\n    std::size_t offset = 0u;\n    if (!read_i32(body, offset, state.credits) ||\n        !read_i32(body, offset, state.power) ||\n        !read_i32(body, offset, state.food) ||\n        !read_i32(body, offset, state.water) ||\n        !read_i32(body, offset, state.rooms) ||\n        !read_i32(body, offset, state.selected_room) ||\n        !read_i32(body, offset, state.assigned_room) ||\n        !read_enum(body, offset, state.selected_build_type) ||\n        !read_i32(body, offset, state.build_cursor_column) ||\n        !read_i32(body, offset, state.build_cursor_floor) ||\n        !read_u64(body, offset, state.next_segment_id)) return false;\n    for (int& value : state.stored) if (!read_i32(body, offset, value)) return false;\n    for (int& value : state.production_steps) if (!read_i32(body, offset, value)) return false;\n    for (auto& room : state.room_entries) {\n        int active = 0;\n        if (!read_i32(body, offset, active) || (active != 0 && active != 1) ||\n            !read_enum(body, offset, room.type) ||\n            !read_i32(body, offset, room.column) ||\n            !read_i32(body, offset, room.floor) ||\n            !read_i32(body, offset, room.stored) ||\n            !read_i32(body, offset, room.production_steps) ||\n            !read_u64(body, offset, room.segment_id) ||\n            !read_u64(body, offset, room.group_id) ||\n            !read_i32(body, offset, room.level)) return false;\n        room.active = active != 0;\n    }\n    for (auto& resident : state.residents) {\n        int active = 0;\n        if (!read_i32(body, offset, active) || (active != 0 && active != 1) ||\n            !read_i32(body, offset, resident.current_column) ||\n            !read_i32(body, offset, resident.current_floor) ||\n            !read_i32(body, offset, resident.next_column) ||\n            !read_i32(body, offset, resident.next_floor) ||\n            !read_i32(body, offset, resident.destination_column) ||\n            !read_i32(body, offset, resident.destination_floor) ||\n            !read_i32(body, offset, resident.assigned_room) ||\n            !read_enum(body, offset, resident.state) ||\n            !read_i32(body, offset, resident.movement_ticks) ||\n            !read_i32(body, offset, resident.roaming_ticks) ||\n            !read_i32(body, offset, resident.roaming_sequence)) return false;\n        resident.active = active != 0;\n    }\n    return offset == body.size() && valid_playable_state(state);\n}\n\n}  // namespace\n'''
rep(anchor,reader,'v3 reader')
rep('''    payload.reserve(kPlayableSavePayloadSizeV2);''','''    payload.reserve(kPlayableSavePayloadSizeV3);''','reserve')
rep('''    append_i32(payload, state.build_cursor_floor);\n    for (const int value : state.stored)''','''    append_i32(payload, state.build_cursor_floor);\n    append_u64(payload, state.next_segment_id);\n    for (const int value : state.stored)''','next id encode')
rep('''        append_i32(payload, room.production_steps);\n    }\n    for (const auto& resident''','''        append_i32(payload, room.production_steps);\n        append_u64(payload, room.segment_id);\n        append_u64(payload, room.group_id);\n        append_i32(payload, room.level);\n    }\n    for (const auto& resident''','room ids encode')
rep('''    if (payload.size() != kPlayableSavePayloadSizeV2) return {};''','''    if (payload.size() != kPlayableSavePayloadSizeV3) return {};''','payload size')
rep('''    append_u16(output, kPlayableSaveVersionV2);''','''    append_u16(output, kPlayableSaveVersionV3);''','encode version')
rep('''        (version != kPlayableSaveVersionV1 &&\n         version != kPlayableSaveVersionV2) ||''','''        (version != kPlayableSaveVersionV1 &&\n         version != kPlayableSaveVersionV2 &&\n         version != kPlayableSaveVersionV3) ||''','accepted version')
rep('''        (version == kPlayableSaveVersionV2 &&\n         payload_size != kPlayableSavePayloadSizeV2) ||''','''        (version == kPlayableSaveVersionV2 &&\n         payload_size != kPlayableSavePayloadSizeV2) ||\n        (version == kPlayableSaveVersionV3 &&\n         payload_size != kPlayableSavePayloadSizeV3) ||''','v3 size')
rep('''    const bool parsed =\n        version == kPlayableSaveVersionV1\n            ? read_v1_payload(body, state)\n            : read_v2_payload(body, state);''','''    const bool parsed =\n        version == kPlayableSaveVersionV1\n            ? read_v1_payload(body, state)\n            : (version == kPlayableSaveVersionV2\n                   ? read_v2_payload(body, state)\n                   : read_v3_payload(body, state));''','parse version')
rep('''    result.migrated_from_v1 =\n        version == kPlayableSaveVersionV1;\n    return result;''','''    result.migrated_from_v1 = version == kPlayableSaveVersionV1;\n    result.migrated_from_v2 = version == kPlayableSaveVersionV2;\n    return result;''','migration flags')
p.write_text(s)

p=Path('tests/playable_shelter_session_tests.cpp')
t=p.read_text()
t=t.replace('void v1_migrates_to_v2_and_atomic_backup_recovers()', 'void legacy_saves_migrate_to_v3_and_atomic_backup_recovers()',1)
t=t.replace('const auto encoded_v2 = encode_playable_state(migrated.state);\n    assert(encoded_v2.size() > make_v1_save().size());\n    assert(encoded_v2[4] == 2u && encoded_v2[5] == 0u);\n\n    auto corrupt = encoded_v2;', 'const auto encoded_v3 = encode_playable_state(migrated.state);\n    assert(encoded_v3.size() > make_v1_save().size());\n    assert(encoded_v3[4] == 3u && encoded_v3[5] == 0u);\n\n    PlayableShelterSession upgraded(migrated.state);\n    assert(upgraded.preview_upgrade_selected().allowed());\n    assert(upgraded.confirm_upgrade_selected() == RoomLifecycleResult::Applied);\n    const auto upgraded_bytes = encode_playable_state(upgraded.state());\n    const auto upgraded_roundtrip = decode_playable_state(upgraded_bytes);\n    assert(upgraded_roundtrip.status == PlayableSaveStatus::Ok);\n    assert(!upgraded_roundtrip.migrated_from_v1);\n    assert(!upgraded_roundtrip.migrated_from_v2);\n    assert(upgraded_roundtrip.state.next_segment_id == upgraded.state().next_segment_id);\n    for (std::size_t index = 0; index < upgraded.state().room_entries.size(); ++index) {\n        const auto& before = upgraded.state().room_entries[index];\n        const auto& after = upgraded_roundtrip.state.room_entries[index];\n        assert(after.segment_id == before.segment_id);\n        assert(after.group_id == before.group_id);\n        assert(after.level == before.level);\n    }\n\n    auto corrupt = encoded_v3;',1)
t=t.replace('    v1_migrates_to_v2_and_atomic_backup_recovers();','    legacy_saves_migrate_to_v3_and_atomic_backup_recovers();',1)
p.write_text(t)
